### PR TITLE
Add deprecation notice to readme files.

### PR DESCRIPTION
**Pull request by johnstonphilip**
Fixes: #24 

Adds a deprecation notice to the readme.md for GitHub, and the readme.txt for WordPress.org.
 
### How to test
Code review. 

### Documentation
Will require documentation updates, notably to:
- https://my.studiopress.com/documentation/genesis-simple-edits/plugin-use/edit-entry-meta-and-footer-info-with-genesis-simple-edits/

cc @susannelson 

@dreamwhisper @nickcernis Do yyou have any knowledge about whether any of our child themes use this plugin in starter packs?

### Notes
Only readme updates — can be pushed to WP.org without a version bump or new zip.

### CODE REVIEW

**Comment by susannelson** [comment]
> This plugin is now deprecated and will no longer receive feature updates. The reason for deprecation is due to the Genesis Framework parent theme allowing similar functionality, which can be found in the WordPress dashboard under
> - Genesis → Theme Settings → Singular Content
> - Genesis → Theme Settings → Header/Footer Scripts

Should the 2nd line be the following instead?

> - Genesis → Theme Settings → Footer

**Comment by johnstonphilip** [comment]
@susannelson This is what I see:

Screen Shot 2020-06-23 at 11 45 10 AM

Is mine showing something different than it should?

**Comment by susannelson** [comment]
Yeah, it looks like you're missing a setting. What version of Genesis and/or what child theme is active? There should be a Footer option as shown here:

image

The Header/Footer Scripts option only allows you to add scripts to the HTML. However, the Footer option allows you to edit the site footer copyright info.

**Comment by susannelson** [comment]
@johnstonphilip Also, if you have Simple Edits activated and the "Modify Entire Footer Text (including markup)?" checkbox is checked, the Footer option won't appear in the customizer.

**Comment by johnstonphilip** [comment]
@susannelson Looks like it was due to my theme, which was the "Elegence" theme, as I was doing a review for the 3rd party. 

That change looks good! Just changed it up. Thank you!

**Comment by susannelson** [comment]
@johnstonphilip The new public facing article has been published: https://my.studiopress.com/documentation/usage/genesis-features/edit-the-entry-meta-and-footer-text-with-genesis/

**Comment by johnstonphilip** [comment]
Just looking for re-approval after adding the link to the doc:
https://github.com/studiopress/genesis-simple-edits/pull/26/commits/2fb120581ec2eb8c8d56801b02e1ca3cb54504ea

**Pull request merged**
